### ISSUE TITLE
Crashing when trying to use replay mod 1.18.1. Using sodium aswell. Is it compatible with sodium tho?

### ISSUE THREAD

**Issue by naasicc** [vram-guild/frex#6]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2022-01-15 11:55
Description: Rendering entity in world

java.lang.ClassCastException: class net.coderbot.iris.layer.IrisRenderTypeWrapper cannot be cast to class net.minecraft.class_1921$class_4687 (net.coderbot.iris.layer.IrisRenderTypeWrapper and net.minecraft.class_1921$class_4687 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @79351f41)
	at io.vram.frex.api.rendertype.RenderTypeUtil.inferPreset(RenderTypeUtil.java:76)
	at io.vram.frex.base.renderer.context.input.BaseBlockInputContext.computeDefaultRenderType(BaseBlockInputContext.java:239)
	at io.vram.frex.base.renderer.context.input.BaseBakedInputContext.defaultPreset(BaseBakedInputContext.java:57)
	at io.vram.frex.base.renderer.context.render.BlockRenderContext.adjustMaterial(BlockRenderContext.java:81)
	at io.vram.frex.base.renderer.context.render.EntityBlockRenderContext.adjustMaterial(EntityBlockRenderContext.java:118)
	at io.vram.frex.base.renderer.context.render.BakedRenderContext.renderQuad(BakedRenderContext.java:42)
	at io.vram.frex.base.renderer.context.render.BaseRenderContext$Emitter.emit(BaseRenderContext.java:84)
	at io.vram.frex.base.renderer.context.render.BaseRenderContext$Emitter.emit(BaseRenderContext.java:75)
	at io.vram.frex.base.renderer.util.BakedModelTranscoder.acceptInsideQuads(BakedModelTranscoder.java:113)
	at io.vram.frex.base.renderer.util.BakedModelTranscoder.accept(BakedModelTranscoder.java:96)
	at io.vram.frex.fabric.compat.FabricContextWrapper.lambda$new$1(FabricContextWrapper.java:67)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.renderAsBlock(FabricBakedModel.java:540)
	at io.vram.frex.base.renderer.context.render.EntityBlockRenderContext.renderItemFrame(EntityBlockRenderContext.java:112)
	at net.minecraft.class_915.redirect$zip000$onRender(class_915.java:560)
	at net.minecraft.class_915.method_3994(class_915.java:79)
	at net.minecraft.class_915.method_3936(class_915.java:27)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1577)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:567)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:471)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:497)
	at net.minecraft.class_761.handler$zkn000$iris$renderTerrainShadows(class_761.java:6465)
	at net.minecraft.class_761.method_22710(class_761.java:1253)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.vram.frex.api.rendertype.RenderTypeUtil.inferPreset(RenderTypeUtil.java:76)
	at io.vram.frex.base.renderer.context.input.BaseBlockInputContext.computeDefaultRenderType(BaseBlockInputContext.java:239)
	at io.vram.frex.base.renderer.context.input.BaseBakedInputContext.defaultPreset(BaseBakedInputContext.java:57)
	at io.vram.frex.base.renderer.context.render.BlockRenderContext.adjustMaterial(BlockRenderContext.java:81)
	at io.vram.frex.base.renderer.context.render.EntityBlockRenderContext.adjustMaterial(EntityBlockRenderContext.java:118)
	at io.vram.frex.base.renderer.context.render.BakedRenderContext.renderQuad(BakedRenderContext.java:42)
	at io.vram.frex.base.renderer.context.render.BaseRenderContext$Emitter.emit(BaseRenderContext.java:84)
	at io.vram.frex.base.renderer.context.render.BaseRenderContext$Emitter.emit(BaseRenderContext.java:75)
	at io.vram.frex.base.renderer.util.BakedModelTranscoder.acceptInsideQuads(BakedModelTranscoder.java:113)
	at io.vram.frex.base.renderer.util.BakedModelTranscoder.accept(BakedModelTranscoder.java:96)
	at io.vram.frex.fabric.compat.FabricContextWrapper.lambda$new$1(FabricContextWrapper.java:67)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.renderAsBlock(FabricBakedModel.java:540)
	at io.vram.frex.base.renderer.context.render.EntityBlockRenderContext.renderItemFrame(EntityBlockRenderContext.java:112)
	at net.minecraft.class_915.redirect$zip000$onRender(class_915.java:560)
	at net.minecraft.class_915.method_3994(class_915.java:79)
	at net.minecraft.class_915.method_3936(class_915.java:27)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1577)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:567)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:471)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:497)
	at net.minecraft.class_761.handler$zkn000$iris$renderTerrainShadows(class_761.java:6465)
	at net.minecraft.class_761.method_22710(class_761.java:1253)
	at net.minecraft.class_757.method_3188(class_757.java:1031)

-- Entity being rendered --
Details:
	Entity Type: minecraft:glow_item_frame (net.minecraft.class_5915)
	Entity ID: 7
	Entity Name: Glow Item Frame
	Entity's Exact location: -94.50, -50.97, 82.50
	Entity's Block location: World: (-95,-51,82), Section: (at 1,13,2 in -6,-4,5; chunk contains blocks -96,-64,80 to -81,319,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1577)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:567)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:471)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:497)
	at net.minecraft.class_761.handler$zkn000$iris$renderTerrainShadows(class_761.java:6465)
	at net.minecraft.class_761.method_22710(class_761.java:1253)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_915@775ed062
	Location: -11.14,-2.28,-11.17 - World: (-12,-3,-12), Section: (at 4,13,4 in -1,-1,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Rotation: 0.0
	Delta: 0.38000262
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1577)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:567)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:471)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:497)
	at net.minecraft.class_761.handler$zkn000$iris$renderTerrainShadows(class_761.java:6465)
	at net.minecraft.class_761.method_22710(class_761.java:1253)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 2 total; [CameraEntity['Roxld'/-1789435, l='ClientLevel', x=-83.36, y=-48.69, z=93.67], class_745['Roxld'/15, l='ClientLevel', x=-83.36, y=-48.69, z=93.67]]
	Chunk stats: 1024, 615
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 338532 game time, 14223 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Better+Leaves+Add-on+V2.5-1.17.zip, aj-crops-get-flowered-lite.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1838850104 bytes (1753 MiB) / 2583691264 bytes (2464 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3,79
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 3072,00
	Graphics card #0 deviceId: 0x1c02
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7208
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192,00
	Memory slot #2 clockSpeed (GHz): 2,13
	Memory slot #2 type: DDR4
	Virtual memory max (MB): 28090,39
	Virtual memory used (MB): 16249,14
	Swap memory total (MB): 3584,00
	Swap memory used (MB): 117,77
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterfpsdist: Better FPS distance Mod 1.18-1.5
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.12
		frex: FREX 6.0.236
		io_vram_bitkit: bitkit 1.0.1
		iris: Iris 1.1.4
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		phosphor: Phosphor 0.8.1
		replaymod: Replay Mod 1.18.1-2.6.3
		sodium: Sodium 0.4.0-alpha5+build.9
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.08, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Better+Leaves+Add-on+V2.5-1.17.zip (incompatible), file/aj-crops-get-flowered-lite.zip (incompatible)
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz

**Comment by spiralhalo** [comment]
You don't need Frex to run ReplayMod. What you need is special Sodium build from the ReplayMod website under "show compatible sodium version". Please read and choose the version carefully. Frex is not currently implemented by Sodium but is hoped to be in the future.
